apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: apps
  labels:
    app: nginx
spec:
  replicas: 2 # Number of pods to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # Using the official NGINX image
        ports:
        - containerPort: 80
