apiVersion: v1
kind: Service
metadata:
  name: k8sgames
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: k8sgames
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
