apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: apps
spec:
  destination:
    server: https://kubernetes.default.svc/
  project: default
  source: 
    repoURL: git@github.com:Prudence-Pulane-Malatjie/k8sgames.git
    path: nginx-deployment/
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
