apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sgames
  namespace: apps
spec:
  project: default
  source:
    repoURL: git@github.com:Prudence-Pulane-Malatjie/k8sgames.git
    path: k8sgames-deployments/k8sgames-helm/templates
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
