apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sgames
  namespace: apps
spec:
  project: default
  source:
    repoURL: myazurecontainer-ang9cxa4brhma9g4.azurecr.io
    path: platform-helm-charts/k8sgames
    targetRevision: 0.1.0
    chart: platform-helm-charts/k8sgames

  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
